// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type Node interface {
	IsNode()
}

type AddNoteInput struct {
	Name string `json:"name"`
}

type AddTodoInput struct {
	Name   string `json:"name"`
	NoteID int    `json:"noteId"`
}

type DeleteNoteInput struct {
	ID int `json:"id"`
}

type Note struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}

func (Note) IsNode() {}

type Todo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   *bool  `json:"done"`
	NoteID int    `json:"noteId"`
}

func (Todo) IsNode() {}

type UpdateNoteInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateTodoInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
