// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type Node interface {
	IsNode()
}

type AddNoteInput struct {
	Name string `json:"name"`
}

type AddNotePayload struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type AddTodoInput struct {
	Name   string `json:"name"`
	Done   *bool  `json:"done"`
	NoteID int    `json:"noteId"`
}

type AddTodoPayload struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   bool   `json:"done"`
	NoteID int    `json:"noteId"`
}

type DeleteNoteInput struct {
	ID int `json:"id"`
}

type DeleteNotePayload struct {
	ID int `json:"id"`
}

type DeleteTodoInput struct {
	ID     int `json:"id"`
	NoteID int `json:"noteId"`
}

type DeleteTodoPayload struct {
	ID     int `json:"id"`
	NoteID int `json:"noteId"`
}

type Note struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}

func (Note) IsNode() {}

type Todo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   bool   `json:"done"`
	NoteID int    `json:"noteId"`
}

func (Todo) IsNode() {}

type ToggleTodoInput struct {
	ID     int `json:"id"`
	NoteID int `json:"noteId"`
}

type ToggleTodoPayload struct {
	ID     int  `json:"id"`
	Done   bool `json:"done"`
	NoteID int  `json:"noteId"`
}

type UpdateNoteInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateNotePayload struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateTodoInput struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   *bool  `json:"done"`
	NoteID int    `json:"noteId"`
}

type UpdateTodoPayload struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   bool   `json:"done"`
	NoteID int    `json:"noteId"`
}
