// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type Note struct {
	ID     int     `json:"id"`
	Name   string  `json:"name"`
	UserID int     `json:"userId"`
	Todos  []*Todo `json:"todos"`
}

func (Note) IsNode() {}

type Todo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Done   *bool  `json:"done"`
	NoteID int    `json:"noteId"`
}

func (Todo) IsNode() {}
